### ISSUE TITLE
Removing the extension does not revert the changes to YouTube

### ISSUE THREAD

**Issue by pierovera** [xxzefgh/youtube-classic-extension#2]
Issue is on Firefox 61.0.1 on Linux

**Comment by cameronswinoga** [comment]
Have you cleared your browser's cache?

**Comment by thisdotvoid** [comment]
Open developer tools (Right Click -> Inspect Element), switch to Storage tab, select Cookies and remove `PREF` cookie

![image](https://user-images.githubusercontent.com/6980903/43188047-439736c0-9004-11e8-8d71-22bc43fa5278.png)

I'm not sure if I can do this programmatically on extension removal.

**Comment by avin3sh** [comment]
Installed fresh copy of Firefox and moved cookies.sqlite from older profile and saw despite not having installed the plugin, YouTube was still loading in classic mode. This solution works.

**Comment by cpeterso** [comment]
Or try uninstalling the extension, logging out of your YouTube account, and then logging back in. That might reset your YouTube cookies.

**Comment by pierovera** [comment]
I managed to fix it by going to https://www.youtube.com/new

**Comment by yanagiragi** [comment]
I used to have the same problem, it turns out to be the same issue as this.

My solution is to modified the "fd" value in "PERF" cookie, it seems like 400 stands for new youtube interface while 42008 get classic youtube webpage.

@xxzefgh perhaps add the URL mentioned from @pierovera on the extension options page provides a better user experience? or maybe on README?

Thanks.

**Comment by xxzefgh** [comment]
@yanagiragi I'll add on/off switch in extension popup menu

**Comment by xxzefgh** [comment]
I've released 1.3 version, hope it doesn't break anything 🙌
