### ISSUE TITLE
list or grid

### ISSUE THREAD

**Issue by morchela** [xxzefgh/youtube-classic-extension#8]
The addon works 99% perfectly, but no matter I change the subscription view to list, when refreshing or reentering it resets to the grid mode

**Comment by morchela** [comment]
Well, I deleted YT cookies and that worked. I hope it'll be fine.

**Comment by extremMiSt** [comment]
is there a doc where the different effects of the pref values are listed/explained? (probs not)
you set f6 to 8 (why?). after that yt changes that to 42008 for me. After switching to list mode it's 42009.
I added the add-on in debugging mode and setting f6 to 42009 keeps it in list mode (mostly). So that's not a good fix >_>

**Comment by xxzefgh** [comment]
@extremMiSt can you test with latest commit? if it works, than I'll publish updated addon

**Comment by extremMiSt** [comment]
hmm..
clicking subs
clicking list view
clicking start
clicking subs
and then it's grid view again
